name: deploy
on:
  push:
    branches:
      - master
      - v3.0.0
    tags:
      - v*
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Deploy the JAR file to the remote server
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Generate the package
        run: mvn clean install -DskipTests -Dmaven.compiler.forceJavacCompilerUse=true
      - name: Deploy the package to the remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          source: target/matstore-0.0.1-SNAPSHOT.jar
          target: app # My remote directory
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: Run a script on remote server (start the application)
        if: always()
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd app/
            kill -9 `cat pid.txt` && rm pid.txt
            nohup java -jar matstore-0.0.1-SNAPSHOT.jar > matstore.log 2>&1 & echo $! > pid.txt
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}